- name: Base configuration
  ansible.builtin.template:
    src: nomad.hcl.j2
    dest: "{{ hashicorp_nomad_config_dir }}/nomad.hcl"
  notify:
    - restart nomad

- name: Deploy master configuration
  ansible.builtin.template:
    src: master.hcl.j2
    dest: "{{ hashicorp_nomad_config_dir }}/master.hcl"
  when: _nomad_master
  notify:
    - restart nomad

- name: Remove master configuration
  ansible.builtin.file:
    path: "{{ hashicorp_nomad_config_dir }}/master.hcl"
    state: absent
  when: not _nomad_master
  notify:
    - restart nomad

- name: Deploy worker configuration
  ansible.builtin.template:
    src: worker.hcl.j2
    dest: "{{ hashicorp_nomad_config_dir }}/worker.hcl"
  when: _nomad_worker
  notify:
    - restart nomad

- name: Remove worker configuration
  ansible.builtin.file:
    path: "{{ hashicorp_nomad_config_dir }}/worker.hcl"
    state: absent
  when: not _nomad_worker
  notify:
    - restart nomad
