---
- name: Install Nomad packages
  ansible.builtin.package:
    name: "{{ hashicorp_nomad_packages }}"

- name: Install additional Python libraries
  ansible.builtin.pip:
    name: "{{ hashicorp_nomad_pip_packages }}"
